[package]
name = "cubeviz"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
svg = "0.18"
structopt = "*"

[[bin]]
name = "cubeviz"
path = "src/bin/cubeviz.rs"
